### ISSUE TITLE
error resolving ppx-flags

### ISSUE THREAD

**Issue by idkjs** [Gregoirevda/reason-apollo-todo-list#1]
Hi @Gregoirevda!

Running the install and start command is throwing an error on ppx-flags. Probably a set up issue on my machine. Do you mind sharing how you are set up to so that opam ppx is working on this project?

Here is the error:
```sh
Module build failed: Error: Fatal error: exception Failure("    at <anonymous>t found when resolving ppx-flags")
```

Thanks

**Comment by idkjs** [comment]
Seems like the solution is to have reason set up with the alternative set up per discord discussion just now. This seems to work. https://reasonml.github.io/docs/en/global-installation.html#alternative-through-opam

**Comment by Gregoirevda** [comment]
So, they're planning to release both packages on npm under `graphql__ppx` which will make it much easier to run

**Comment by idkjs** [comment]
FYI. Im looking for a reasonml/javascript internship/job, coding or code knowledgeable customer relations in case you are aware of anything. Figured i'd mention it since your company seems to do that type of thing. Thanks for sharing your work!

**Comment by Gregoirevda** [comment]
@hackages Can you contact this great dev please?
